AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AppHelix_CoursePlatform

  Sample SAM Template for AppHelix_CoursePlatform

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        DB_HOST: host.docker.internal
        DB_USER: postgres
        DB_PASS: root
        DB_PORT: "5433"
        DB_NAME: apphelix_db

Resources:
  DatabaseNameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: server/
      Handler: app.handler
      Runtime: nodejs18.x
      Events:
        DatabaseName:
          Type: Api
          Properties:
            Path: /database
            Method: get

  StudentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: server/
      Handler: app.studentRouterHandler
      Runtime: nodejs18.x
      Events:
        RegisterStudentApi:
          Type: Api
          Properties:
            Path: /student
            Method: post
        GetStudentApi:
          Type: Api
          Properties:
            Path: /student
            Method: get
        GetStudentByIdApi:
          Type: Api
          Properties:
            Path: /student/{id}
            Method: get
        UpdateStudentApi:
          Type: Api
          Properties:
            Path: /student/{id}
            Method: put
        DeleteStudentApi:
          Type: Api
          Properties:
            Path: /student/{id}
            Method: delete
  CourseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: server/
      Handler: app.courseRouterHandler
      Runtime: nodejs18.x
      Events:
        AddCourseApi:
          Type: Api
          Properties:
            Path: /course
            Method: post
        GetCourseApi:
          Type: Api
          Properties:
            Path: /course
            Method: get
        GetCourseByIdApi:
          Type: Api
          Properties:
            Path: /course/{id}
            Method: get
        UpdateCourseApi:
          Type: Api
          Properties:
            Path: /course/{id}
            Method: put
        DeleteCourseApi:
          Type: Api
          Properties:
            Path: /course/{id}
            Method: delete
  EnrollmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: server/
      Handler: app.enrollmentRouterHandler
      Runtime: nodejs18.x
      Events:
        EnrollApi:
          Type: Api
          Properties:
            Path: /enroll
            Method: post
        GetEnrollmentsApi:
          Type: Api
          Properties:
            Path: /enroll
            Method: get
        MarkCompletionApi:
          Type: Api
          Properties:
            Path: /completion
            Method: put

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"
Outputs:
  DatabaseApiEndpoint:
    Description: API Gateway endpoint URL for the /database route
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/database"
